language: node_js
node_js:
  - 8.5.0
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
jobs:
  include:
    - stage: test & deploy
      script: skip
      before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      script:
      - npm run ci
      before_deploy:
      - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - npm run build:prod
      - mkdir build
      - cp -r dist build/dist
      - cd server
      - npm install
      - cd ../
      - cp -r server build/server
      - tar -czf package.tgz build
      - openssl aes-256-cbc -K $encrypted_a203ffbb8517_key -iv $encrypted_a203ffbb8517_iv
        -in id_rsa.enc -out id_rsa -d
      - eval "$(ssh-agent -s)"
      - chmod 600 id_rsa
      - ssh-add id_rsa
      - scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:/home/deploy/front-dev
      deploy:
        provider: script
        script:
        - ssh $DEPLOY_USER@$DEPLOY_HOST sh /home/deploy/front-dev/scripts/deploy.sh
        on:
          branch: develop
env:
  global:
  - secure: gUsVk41xMgBzMIG4LK3Miu7N+zxM/lXdRcjC1LtvxTcyauEJS3CsO21ML7lN2JWcp1Vui9zWV8j9w6UOo6nhsYxRfRkqRTf+jEPmUcSONrY5AAE1MmbuMYOkm4rYQr1zpgguMc9vMMGDbL0J/9KYocQXLK2TU5NyEcN5e2wRl+u91Ntu2/vroUmElhRyDUUkLp/mLxU/HOPyjO7DcAGACM5G6E6f37/1n8cFmu/BJMx0uOzFuDnUfeDUiMqShWphgyzgEBUiRVPT/MZboqTd+0yK9QriYf7x0SWZuaWfwLHaZpUz1zZ9AlxFKvf3+uK4IBJw3yCgeIqKt7aoHgRLMVhChrONbHCcD2flUtieWd7odIc2sOmtf/ya0KolnnT6DATyBp7Wr6u1lyzgC8wwBfAQdQmyefnOh/Uv/tPD/pv0EvNGTmUPmLIgzg+Y2Lef2bDs/AYCRoJwHGcDomZTAxvhI6sb4t55K5zGobjKdirhczhsbKgdvR/kZ6oAcKeXIZcrTOVFbti/NJ6geyGBvH+kHYx7vz3XtAKIlCFZJffYODDPg4IpQTSKk+6wu3s1gByNuvKOvgORE0oSU7fSZ4FW1v9YuSgM3mJ2FypQW3bbk14Wqv3vA17rZpOz4YW/Vk97o1o2b7DyMKI4317Sg50kzDsWCfwK88H46Jne8PE=
  - secure: SnzffB/82VbCDOk2oKoM1Pvsp13xdTz+eAMh+EONcE9uyfv7kB2rm29GKTlHaJhWt1ny/YxekTK+lhnYXFTe0FeEgrh7BE8MHQL5ipK7az5DLg6oolfQK61g9sS+f+LANJphKnH89leonjyiZjWvMYE6SQWSA+XYDLf3XLTEUSHEDXz4+lIZ1nIe8+lyDsvnH6+7FnosFD8ABEXCbDT+WF45CSvQsoq3k3K/MgH6AxJSOXuwCMsoSmfuhK39fa+OvkSLdXt6QuC3L7S8Y9/P1e7qLb/s/43zzlXQJyaOcXfEdA+ZZRwFJnIperwO6dv4BTMhMQ0hI7Tes0f1og8fMNKnjcV4FCae1Fh4Otpu727kOPQxr7xaU/7zQjvFC7NNMNafKSe09IiziebZat5RhQGBLPFC8ldOafYvPfgscewMf+aSerQtboaYVbQYXh2R6riiJCM8EDcIFVCrXXG4YGMdXvUo90uetRPMT8eoYQwx16n0je2Ude32cRPxkY5CqJJu9zLCVie2wjbbaKfgIprrklFE9BIGcPwB+kG3NsBlHYX+yxoeUu2sGBI+2S8Npldt2RcLznRdmeTf0t7oJxvgdmPN4NxEr8sAE9p4UrQ01gm4neyjSWSIiJ+igSbBLDDtvQFAGmKo6abyGRIS/U66KWYlEDURXVQbdc+9csI=
